//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizhu
    {
        public System.Guid id { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> steps { get; set; }
        public string hanlder { get; set; }
        public string detail { get; set; }
    }
}
