//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class GtestUser
    {
        public int userid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string shuliang { get; set; }
        public string bumen { get; set; }
        public string tel { get; set; }
        public string dengluma { get; set; }
        public string zhiwei { get; set; }
        public string userxm { get; set; }
    }
}
