//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gtestbiaodan
    {
        public string id { get; set; }
        public Nullable<System.DateTime> tbrq { get; set; }
        public string tbbm { get; set; }
        public string tbrgh { get; set; }
        public Nullable<System.DateTime> cxrq { get; set; }
        public string ycgx { get; set; }
        public string zrbm { get; set; }
        public string btzr { get; set; }
        public string wlmc { get; set; }
        public string wlxh { get; set; }
        public string ph { get; set; }
        public string sb { get; set; }
        public string sbbh { get; set; }
        public string gsbgp { get; set; }
        public string zt { get; set; }
        public string ycfl { get; set; }
        public string ycms { get; set; }
        public string zrrgh { get; set; }
        public string gjc { get; set; }
        public string yyfx { get; set; }
        public string zgjg { get; set; }
        public string gsbg { get; set; }
        public Nullable<System.DateTime> wcrq { get; set; }
        public string xgqr { get; set; }
        public Nullable<int> bdzt { get; set; }
        public Nullable<System.DateTime> gbrq { get; set; }
        public Nullable<int> fouce { get; set; }
        public Nullable<int> zsjl { get; set; }
        public Nullable<System.DateTime> zfrq { get; set; }
        public Nullable<System.DateTime> xyrq { get; set; }
        public Nullable<int> gbzt { get; set; }
    }
}
