//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class KeSuChanPinYWY
    {
        public System.Guid id { get; set; }
        public Nullable<int> bid { get; set; }
        public string ddh { get; set; }
        public Nullable<int> sl { get; set; }
        public string yy { get; set; }
        public string thh { get; set; }
        public string wt { get; set; }
    }
}
