//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProcessManagerDbEntities : DbContext
    {
        public ProcessManagerDbEntities()
            : base("name=ProcessManagerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basice> Basice { get; set; }
        public virtual DbSet<Chaosong> Chaosong { get; set; }
        public virtual DbSet<Huiqian> Huiqian { get; set; }
        public virtual DbSet<Pizhu> Pizhu { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<Predefine> Predefine { get; set; }
        public virtual DbSet<QingjiaDan> QingjiaDan { get; set; }
        public virtual DbSet<FuZeRen> FuZeRen { get; set; }
        public virtual DbSet<BiaoList> BiaoList { get; set; }
        public virtual DbSet<KeSuChanPinYWY> KeSuChanPinYWY { get; set; }
        public virtual DbSet<KeSuChanPinZZ> KeSuChanPinZZ { get; set; }
        public virtual DbSet<KeSuDan> KeSuDan { get; set; }
        public virtual DbSet<BaoCun> BaoCun { get; set; }
    }
}
