//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class QingjiaDan
    {
        public System.Guid id { get; set; }
        public Nullable<int> bid { get; set; }
        public Nullable<int> pid { get; set; }
        public string leixing { get; set; }
        public Nullable<System.DateTime> startime { get; set; }
        public Nullable<System.DateTime> finishtime { get; set; }
        public Nullable<int> tianshu { get; set; }
        public string shenqingren { get; set; }
        public Nullable<System.DateTime> tijiaotime { get; set; }
        public string detil { get; set; }
    }
}
