//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TJZHEntities : DbContext
    {
        public TJZHEntities()
            : base("name=TJZHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GtestUser> GtestUser { get; set; }
        public virtual DbSet<Gtestbiaodan> Gtestbiaodan { get; set; }
        public virtual DbSet<YiChangFenLei> YiChangFenLei { get; set; }
        public virtual DbSet<YiChangFuZeRen> YiChangFuZeRen { get; set; }
        public virtual DbSet<YiChangCuLi> YiChangCuLi { get; set; }
    }
}
