//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class YiChangCuLi
    {
        public System.Guid id { get; set; }
        public string yichangid { get; set; }
        public string yyfx { get; set; }
        public string zgjg { get; set; }
        public string xgqr { get; set; }
        public Nullable<System.DateTime> culitime { get; set; }
        public Nullable<System.DateTime> querentime { get; set; }
        public string leixing { get; set; }
        public string flag { get; set; }
        public string culiren { get; set; }
    }
}
